name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: |
            go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=30m

      - name: Go Vet
        run: go vet ./...

      - name: Run tests
        env:
          CGO_ENABLED: 1
        run: |
          go test -race ./...
